### ISSUE TITLE
typo in next_trn_id()

### ISSUE THREAD

**Issue by tjko** [jfraire/Device-Modbus-TCP#2]
It seems there is typo in the range check ?

      $trans_id = 1 if $trans_id > 65_535;

Above probably was meant to be:

      $trans_id = 1 if $trans_id > 65535;

**Comment by jfraire** [comment]
In Perl, 65_535 == 65535:

 ```
use strict;
 use warnings;
 use v5.20;

 say 65_535 == 65535 ? 'Yes' : 'No';
```
