### ISSUE TITLE
Missing prerequisite in  $ perl Makefile.PL

### ISSUE THREAD

**Issue by mcmellow** [jfraire/Device-Modbus-TCP#3]
Cannot run perl Makefile.PL because of missing prerequisites. See log line below

/home/pi/Device-Modbus-TCP$ perl Makefile.PL
Warning: prerequisite Device::Modbus 0.021 not found.
Warning: prerequisite Net::Server 2.008 not found.
Warning: prerequisite Role::Tiny 2 not found.
Warning: prerequisite Try::Tiny 0.22 not found.
Generating a Unix-style Makefile
Writing Makefile for Device::Modbus::TCP
Writing MYMETA.yml and MYMETA.json

Where can i find the needed prerequisites?
Thanks in advance

**Comment by jfraire** [comment]
Hello.
Prerequisites can be installed from CPAN, the repository for Perl modules. I recommend you to use cpanm, see https://cpanmin.us/ for instructions. The standard way to install Perl modules from CPAN is through the cpan command, which is very likely to be installed in your machine already. Both tools will take care of prerequisites.
